import { EXTRA_TESTS } from './extraTests';
import { 
  LabTest, 
  HealthPackage, 
  LabOrder, 
  Booking, 
  LabSettings, 
  LoyaltyCard, 
  StaffMember, 
  AttendanceRecord, 
  FinancialTransaction, 
  InventoryItem 
} from '../types';

const BASE_TESTS: LabTest[] = [
  {
    id: 'test-cbc',
    code: 'CBC-01',
    nameEn: 'Complete Blood Count (CBC)',
    nameAr: 'صورة دم كاملة وديناميكية كرات الدم',
    category: 'hematology',
    categoryAr: 'أمراض الدم والهماتولوجي',
    sampleType: 'Whole Blood (EDTA)',
    tubeColor: 'purple',
    tubeName: 'أنبوب لافندر (EDTA Tube)',
    turnaroundHours: 2,
    fastingHours: 0,
    instructionsAr: 'لا يشترط الصيام. يمكن إجراؤه في أي وقت من اليوم.',
    price: 180,
    parameters: [
      { id: 'hb', nameEn: 'Hemoglobin (Hb)', nameAr: 'الهيموجلوبين', unit: 'g/dL', defaultRefMin: 13.0, defaultRefMax: 17.5, refMale: '13.0 - 17.5', refFemale: '12.0 - 15.5', panicMin: 7.0, panicMax: 20.0 },
      { id: 'rbc', nameEn: 'RBC Count', nameAr: 'كرات الدم الحمراء', unit: 'x10^6/uL', defaultRefMin: 4.5, defaultRefMax: 5.9, refMale: '4.5 - 5.9', refFemale: '4.0 - 5.2' },
      { id: 'hct', nameEn: 'Hematocrit (PCV)', nameAr: 'نسبة حجم الخلايا المكدسة', unit: '%', defaultRefMin: 40.0, defaultRefMax: 50.0, refMale: '40.0 - 50.0', refFemale: '36.0 - 46.0' },
      { id: 'mcv', nameEn: 'MCV', nameAr: 'متوسط حجم الخلية', unit: 'fL', defaultRefMin: 80.0, defaultRefMax: 98.0, refText: '80.0 - 98.0' },
      { id: 'mch', nameEn: 'MCH', nameAr: 'متوسط وزن الهيموجلوبين', unit: 'pg', defaultRefMin: 27.0, defaultRefMax: 33.0, refText: '27.0 - 33.0' },
      { id: 'mchc', nameEn: 'MCHC', nameAr: 'تركيز الهيموجلوبين بالكرية', unit: 'g/dL', defaultRefMin: 32.0, defaultRefMax: 36.0, refText: '32.0 - 36.0' },
      { id: 'rdw', nameEn: 'RDW-CV', nameAr: 'مؤشر تباين حجم الكرات الحمراء', unit: '%', defaultRefMin: 11.5, defaultRefMax: 14.5, refText: '11.5 - 14.5' },
      { id: 'plt', nameEn: 'Platelets Count', nameAr: 'الصفائح الدموية', unit: 'x10^3/uL', defaultRefMin: 150, defaultRefMax: 450, refText: '150 - 450', panicMin: 50, panicMax: 1000 },
      { id: 'wbc', nameEn: 'Total WBC Count', nameAr: 'إجمالي كرات الدم البيضاء', unit: 'x10^3/uL', defaultRefMin: 4.0, defaultRefMax: 11.0, refText: '4.0 - 11.0', panicMin: 2.0, panicMax: 30.0 },
      { id: 'neut_pct', nameEn: 'Neutrophils %', nameAr: 'الخلايا المتعادلة %', unit: '%', defaultRefMin: 40.0, defaultRefMax: 70.0, refText: '40.0 - 70.0' },
      { id: 'lymph_pct', nameEn: 'Lymphocytes %', nameAr: 'الخلايا الليمفاوية %', unit: '%', defaultRefMin: 20.0, defaultRefMax: 45.0, refText: '20.0 - 45.0' },
      { id: 'mono_pct', nameEn: 'Monocytes %', nameAr: 'الخلايا وحيدة النواة %', unit: '%', defaultRefMin: 2.0, defaultRefMax: 8.0, refText: '2.0 - 8.0' },
      { id: 'eos_pct', nameEn: 'Eosinophils %', nameAr: 'الخلايا الحمضية %', unit: '%', defaultRefMin: 1.0, defaultRefMax: 5.0, refText: '1.0 - 5.0' },
      { id: 'baso_pct', nameEn: 'Basophils %', nameAr: 'الخلايا القاعدية %', unit: '%', defaultRefMin: 0.0, defaultRefMax: 1.0, refText: '0.0 - 1.0' },
    ]
  },
  {
    id: 'test-esr',
    code: 'ESR-02',
    nameEn: 'Erythrocyte Sedimentation Rate (ESR)',
    nameAr: 'سرعة ترسب كرات الدم الحمراء',
    category: 'hematology',
    categoryAr: 'أمراض الدم والهماتولوجي',
    sampleType: 'Whole Blood (Citrate)',
    tubeColor: 'blue',
    tubeName: 'أنبوب ستريت أسود/أزرق',
    turnaroundHours: 2,
    fastingHours: 0,
    instructionsAr: 'لا يتطلب صيام مسبق.',
    price: 80,
    parameters: [
      { id: 'esr_1hr', nameEn: 'ESR (1st Hour)', nameAr: 'سرعة الترسيب (الساعة الأولى)', unit: 'mm/hr', defaultRefMin: 0, defaultRefMax: 15, refMale: '0 - 15', refFemale: '0 - 20' },
      { id: 'esr_2hr', nameEn: 'ESR (2nd Hour)', nameAr: 'سرعة الترسيب (الساعة الثانية)', unit: 'mm/hr', defaultRefMin: 0, defaultRefMax: 30, refMale: '0 - 30', refFemale: '0 - 35' }
    ]
  },
  {
    id: 'test-liver',
    code: 'LFT-03',
    nameEn: 'Liver Function Panel (Full)',
    nameAr: 'وظائف الكبد الكاملة',
    category: 'liver',
    categoryAr: 'وظائف الكبد والإنزيمات',
    sampleType: 'Serum (Gel Separator)',
    tubeColor: 'yellow',
    tubeName: 'أنبوب جل أصفر (Gel SST)',
    turnaroundHours: 3,
    fastingHours: 6,
    instructionsAr: 'يفضل الصيام من 4 إلى 6 ساعات قبل سحب العينة.',
    price: 240,
    parameters: [
      { id: 'alt', nameEn: 'ALT (SGPT)', nameAr: 'إنزيم الكبد (ALT)', unit: 'U/L', defaultRefMin: 7, defaultRefMax: 45, refMale: 'Up to 45', refFemale: 'Up to 34' },
      { id: 'ast', nameEn: 'AST (SGOT)', nameAr: 'إنزيم الكبد (AST)', unit: 'U/L', defaultRefMin: 8, defaultRefMax: 40, refMale: 'Up to 40', refFemale: 'Up to 35' },
      { id: 'tot_bili', nameEn: 'Total Bilirubin', nameAr: 'الصفراء الكلية بالدم', unit: 'mg/dL', defaultRefMin: 0.2, defaultRefMax: 1.2, refText: '0.2 - 1.2' },
      { id: 'dir_bili', nameEn: 'Direct Bilirubin', nameAr: 'الصفراء المباشرة', unit: 'mg/dL', defaultRefMin: 0.0, defaultRefMax: 0.3, refText: 'Up to 0.3' },
      { id: 'indir_bili', nameEn: 'Indirect Bilirubin', nameAr: 'الصفراء غير المباشرة (محسوبة)', unit: 'mg/dL', defaultRefMin: 0.1, defaultRefMax: 0.8, refText: '0.1 - 0.8', isCalculated: true },
      { id: 'alp', nameEn: 'Alkaline Phosphatase (ALP)', nameAr: 'الفوسفاتاز القلوي', unit: 'U/L', defaultRefMin: 40, defaultRefMax: 130, refText: '40 - 130' },
      { id: 'tot_prot', nameEn: 'Total Protein', nameAr: 'البروتين الكلي', unit: 'g/dL', defaultRefMin: 6.4, defaultRefMax: 8.3, refText: '6.4 - 8.3' },
      { id: 'albumin', nameEn: 'Serum Albumin', nameAr: 'الألبومين', unit: 'g/dL', defaultRefMin: 3.5, defaultRefMax: 5.2, refText: '3.5 - 5.2' },
      { id: 'globulin', nameEn: 'Serum Globulin', nameAr: 'الجلوبيولين (محسوب)', unit: 'g/dL', defaultRefMin: 2.0, defaultRefMax: 3.5, refText: '2.0 - 3.5', isCalculated: true },
      { id: 'ag_ratio', nameEn: 'A/G Ratio', nameAr: 'نسبة الألبومين للجلوبيولين', unit: 'Ratio', defaultRefMin: 1.2, defaultRefMax: 2.2, refText: '1.2 - 2.2', isCalculated: true },
    ]
  },
  {
    id: 'test-kidney',
    code: 'KFT-04',
    nameEn: 'Kidney Function & Electrolytes Panel',
    nameAr: 'وظائف الكلى والأملاح الحيوية',
    category: 'kidney',
    categoryAr: 'وظائف الكلى والأملاح',
    sampleType: 'Serum (Gel Separator)',
    tubeColor: 'yellow',
    tubeName: 'أنبوب جل أصفر (Gel SST)',
    turnaroundHours: 3,
    fastingHours: 0,
    instructionsAr: 'يستحسن شرب الماء وتجنب التمارين العنيفة قبل الفحص.',
    price: 220,
    parameters: [
      { id: 'creatinine', nameEn: 'Serum Creatinine', nameAr: 'الكرياتينين بالدم', unit: 'mg/dL', defaultRefMin: 0.6, defaultRefMax: 1.2, refMale: '0.7 - 1.2', refFemale: '0.5 - 1.0', panicMax: 4.0 },
      { id: 'urea', nameEn: 'Blood Urea', nameAr: 'البولينا بالدم (اليوريا)', unit: 'mg/dL', defaultRefMin: 15, defaultRefMax: 45, refText: '15 - 45' },
      { id: 'uric_acid', nameEn: 'Serum Uric Acid', nameAr: 'حمض اليوريك (النقرس)', unit: 'mg/dL', defaultRefMin: 3.5, defaultRefMax: 7.2, refMale: '3.5 - 7.2', refFemale: '2.6 - 6.0' },
      { id: 'egfr', nameEn: 'eGFR (CKD-EPI)', nameAr: 'معدل الترشيح الكلوي التقديري', unit: 'mL/min/1.73m2', defaultRefMin: 90, defaultRefMax: 130, refText: '> 90 (Normal renal function)', isCalculated: true },
      { id: 'sodium', nameEn: 'Sodium (Na+)', nameAr: 'الصوديوم', unit: 'mmol/L', defaultRefMin: 135, defaultRefMax: 145, refText: '135 - 145', panicMin: 120, panicMax: 160 },
      { id: 'potassium', nameEn: 'Potassium (K+)', nameAr: 'البوتاسيوم', unit: 'mmol/L', defaultRefMin: 3.5, defaultRefMax: 5.1, refText: '3.5 - 5.1', panicMin: 2.8, panicMax: 6.2 },
      { id: 'calcium', nameEn: 'Total Calcium', nameAr: 'الكالسيوم الكلي', unit: 'mg/dL', defaultRefMin: 8.6, defaultRefMax: 10.3, refText: '8.6 - 10.3' }
    ]
  },
  {
    id: 'test-diabetes',
    code: 'GLU-05',
    nameEn: 'Diabetes Comprehensive Screening',
    nameAr: 'فحص السكر الشامل والتراكمي ومقاومة الإنسولين',
    category: 'diabetes',
    categoryAr: 'داء السكري والغدد الصماء',
    sampleType: 'Serum / Fluoride & EDTA',
    tubeColor: 'grey',
    tubeName: 'أنبوب فلورايد رمادي + إيديتا بنفسجي',
    turnaroundHours: 2,
    fastingHours: 8,
    instructionsAr: 'يشترط الصيام التام عن الطعام والشراب (ما عدا الماء النقي) لمدة 8 إلى 10 ساعات.',
    price: 250,
    parameters: [
      { id: 'fbg', nameEn: 'Fasting Blood Glucose', nameAr: 'السكر الصائم بالدم', unit: 'mg/dL', defaultRefMin: 70, defaultRefMax: 99, refText: '70 - 99 Normal | 100 - 125 Prediabetes | >= 126 Diabetes', panicMin: 50, panicMax: 400 },
      { id: 'hba1c', nameEn: 'HbA1c (Glycated Hemoglobin)', nameAr: 'السكر التراكمي (الهيموجلوبين السكري)', unit: '%', defaultRefMin: 4.0, defaultRefMax: 5.6, refText: '< 5.7 Normal | 5.7 - 6.4 Prediabetes | >= 6.5 Diabetes' },
      { id: 'eag', nameEn: 'Estimated Average Glucose (eAG)', nameAr: 'متوسط السكر التقديري المحسوب', unit: 'mg/dL', defaultRefMin: 68, defaultRefMax: 114, refText: '68 - 114 mg/dL', isCalculated: true },
      { id: 'fasting_insulin', nameEn: 'Fasting Serum Insulin', nameAr: 'إنسولين الدم الصائم', unit: 'uIU/mL', defaultRefMin: 2.6, defaultRefMax: 24.9, refText: '2.6 - 24.9' },
      { id: 'homa_ir', nameEn: 'HOMA-IR (Insulin Resistance)', nameAr: 'مؤشر مقاومة الإنسولين (HOMA-IR)', unit: 'Index', defaultRefMin: 0.5, defaultRefMax: 1.9, refText: '< 1.9 Normal | 1.9 - 2.9 Early Resistance | > 2.9 High Resistance', isCalculated: true }
    ]
  },
  {
    id: 'test-lipids',
    code: 'LIP-06',
    nameEn: 'Lipid Profile (Full Heart Health)',
    nameAr: 'دهون الدم الكاملة وصحة القلب والشرايين',
    category: 'lipids',
    categoryAr: 'الدهون وصحة القلب',
    sampleType: 'Serum (Gel Separator)',
    tubeColor: 'yellow',
    tubeName: 'أنبوب جل أصفر (Gel SST)',
    turnaroundHours: 3,
    fastingHours: 12,
    instructionsAr: 'يشترط الصيام التام من 10 إلى 12 ساعة متواصلة مع السماح بشرب الماء فقط.',
    price: 210,
    parameters: [
      { id: 'chol', nameEn: 'Total Cholesterol', nameAr: 'الكوليسترول الكلي', unit: 'mg/dL', defaultRefMin: 120, defaultRefMax: 200, refText: '< 200 Desirable | 200 - 239 Borderline | >= 240 High' },
      { id: 'trig', nameEn: 'Triglycerides', nameAr: 'الدهون الثلاثية', unit: 'mg/dL', defaultRefMin: 50, defaultRefMax: 150, refText: '< 150 Normal | 150 - 199 Borderline | >= 200 High' },
      { id: 'hdl', nameEn: 'HDL Cholesterol (Good)', nameAr: 'الكوليسترول عالي الكثافة (النافع)', unit: 'mg/dL', defaultRefMin: 40, defaultRefMax: 60, refMale: '> 40 mg/dL', refFemale: '> 50 mg/dL' },
      { id: 'ldl', nameEn: 'LDL Cholesterol (Bad)', nameAr: 'الكوليسترول منخفض الكثافة (الضار)', unit: 'mg/dL', defaultRefMin: 50, defaultRefMax: 100, refText: '< 100 Optimal | 100 - 129 Near Optimal | 130 - 159 Borderline High | >= 160 High', isCalculated: true },
      { id: 'vldl', nameEn: 'VLDL Cholesterol', nameAr: 'كوليسترول منخفض الكثافة جداً', unit: 'mg/dL', defaultRefMin: 10, defaultRefMax: 30, refText: '10 - 30', isCalculated: true },
      { id: 'chol_hdl_ratio', nameEn: 'Cholesterol / HDL Ratio', nameAr: 'مؤشر خطورة تصلب الشرايين', unit: 'Ratio', defaultRefMin: 2.5, defaultRefMax: 4.5, refText: '< 4.5 (Lower is better cardiovascular safety)', isCalculated: true }
    ]
  },
  {
    id: 'test-thyroid',
    code: 'THY-07',
    nameEn: 'Thyroid Function Panel (TSH, FT3, FT4)',
    nameAr: 'وظائف الغدة الدرقية الكاملة',
    category: 'thyroid',
    categoryAr: 'الغدد الصماء والهرمونات',
    sampleType: 'Serum (Gel Separator)',
    tubeColor: 'yellow',
    tubeName: 'أنبوب جل أصفر (Gel SST)',
    turnaroundHours: 4,
    fastingHours: 0,
    instructionsAr: 'يفضل سحب العينة صباحاً، وإبلاغ المختبر في حال تناول أدوية الغدة (الثايروكسين).',
    price: 320,
    parameters: [
      { id: 'tsh', nameEn: 'TSH (Ultrasensitive)', nameAr: 'الهرمون المنبه للغدة الدرقية (TSH)', unit: 'uIU/mL', defaultRefMin: 0.4, defaultRefMax: 4.2, refText: '0.4 - 4.2', panicMin: 0.05, panicMax: 20.0 },
      { id: 'ft3', nameEn: 'Free T3 (FT3)', nameAr: 'هرمون ثلاثي اليودوثيرونين الحر', unit: 'pg/mL', defaultRefMin: 2.0, defaultRefMax: 4.4, refText: '2.0 - 4.4' },
      { id: 'ft4', nameEn: 'Free T4 (FT4)', nameAr: 'هرمون الثيروكسين الحر', unit: 'ng/dL', defaultRefMin: 0.93, defaultRefMax: 1.7, refText: '0.93 - 1.70' }
    ]
  },
  {
    id: 'test-vitamins',
    code: 'VIT-08',
    nameEn: 'Vitamins & Vitality (D3, B12, Ferritin)',
    nameAr: 'فيتامين د3 وفيتامين ب12 ومخزون الحديد',
    category: 'vitamins',
    categoryAr: 'الفيتامينات والمعادن والنشاط',
    sampleType: 'Serum (Protected from Light)',
    tubeColor: 'yellow',
    tubeName: 'أنبوب جل أصفر مع الحماية من الضوء',
    turnaroundHours: 5,
    fastingHours: 6,
    instructionsAr: 'يفضل الصيام 6 ساعات. تجنب المكملات الغذائية لمدة 24 ساعة قبل التحليل.',
    price: 490,
    parameters: [
      { id: 'vit_d', nameEn: '25-OH Vitamin D Total', nameAr: 'فيتامين د الكلي', unit: 'ng/mL', defaultRefMin: 30, defaultRefMax: 100, refText: '< 20 Deficient | 20 - 30 Insufficient | 30 - 100 Sufficient | > 100 Toxicity' },
      { id: 'vit_b12', nameEn: 'Vitamin B12 (Cobalamin)', nameAr: 'فيتامين ب12', unit: 'pg/mL', defaultRefMin: 200, defaultRefMax: 900, refText: '200 - 900 pg/mL' },
      { id: 'ferritin', nameEn: 'Serum Ferritin', nameAr: 'الفيريتين (مخزون الحديد)', unit: 'ng/mL', defaultRefMin: 30, defaultRefMax: 300, refMale: '30 - 300', refFemale: '15 - 200' },
      { id: 'serum_iron', nameEn: 'Serum Iron', nameAr: 'الحديد بالدم', unit: 'ug/dL', defaultRefMin: 60, defaultRefMax: 170, refMale: '65 - 175', refFemale: '50 - 170' }
    ]
  },
  {
    id: 'test-coag',
    code: 'COAG-09',
    nameEn: 'Coagulation Profile (PT, INR, PTT)',
    nameAr: 'فحوصات السيولة والتخثر وزمن البروثرومبين',
    category: 'coagulation',
    categoryAr: 'السيولة والتخثر',
    sampleType: 'Plasma (Sodium Citrate 3.2%)',
    tubeColor: 'blue',
    tubeName: 'أنبوب ستريت أزرق سماوي (Citrate Tube)',
    turnaroundHours: 2,
    fastingHours: 0,
    instructionsAr: 'يجب ملء الأنبوب حتى العلامة المحددة بدقة. إعلام المختبر في حال تناول مسيلات دم مثل الوارفارين أو الأسبرين.',
    price: 190,
    parameters: [
      { id: 'pt_patient', nameEn: 'Prothrombin Time (PT)', nameAr: 'زمن البروثرومبين', unit: 'Seconds', defaultRefMin: 11.0, defaultRefMax: 13.5, refText: '11.0 - 13.5 sec' },
      { id: 'pt_activity', nameEn: 'Prothrombin Activity', nameAr: 'نشاط البروثرومبين', unit: '%', defaultRefMin: 70, defaultRefMax: 100, refText: '70 - 100 %' },
      { id: 'inr', nameEn: 'INR', nameAr: 'معدل التخثر الدولي (INR)', unit: 'Ratio', defaultRefMin: 0.85, defaultRefMax: 1.15, refText: 'Normal: 0.85 - 1.15 | On Warfarin therapy: 2.0 - 3.0', panicMax: 4.5 },
      { id: 'ptt', nameEn: 'PTT (Partial Thromboplastin Time)', nameAr: 'زمن الثرومبوبلاستين الجزئي', unit: 'Seconds', defaultRefMin: 25.0, defaultRefMax: 35.0, refText: '25.0 - 35.0 sec' }
    ]
  },
  {
    id: 'test-urine',
    code: 'URN-10',
    nameEn: 'Complete Urinalysis (Physical, Chemical & Microscopic)',
    nameAr: 'تحليل البول الكامل (فزيائي، كيميائي، وميكروسكوبي)',
    category: 'urine',
    categoryAr: 'الفحص الميكروسكوبي وسوائل الجسم',
    sampleType: 'Fresh Midstream Urine',
    tubeColor: 'sterile_cup',
    tubeName: 'وعاء معقم لجمع عينات البول (Sterile Container)',
    turnaroundHours: 1,
    fastingHours: 0,
    instructionsAr: 'يفضل أول عينة بول صباحية بعد غسيل موضعي بالماء، وأخذ منتصف مجرى البول (Midstream).',
    price: 90,
    parameters: [
      // Physical
      { id: 'urn_color', nameEn: 'Color', nameAr: 'اللون', unit: '', refText: 'Pale Yellow / Yellow', options: ['Pale Yellow', 'Yellow', 'Amber', 'Reddish', 'Brownish', 'Straw'] },
      { id: 'urn_aspect', nameEn: 'Aspect / Clarity', nameAr: 'المظهر والشفافية', unit: '', refText: 'Clear', options: ['Clear', 'Hazy', 'Turbid', 'Semi-turbid'] },
      { id: 'urn_sg', nameEn: 'Specific Gravity', nameAr: 'الكثافة النوعية', unit: '', defaultRefMin: 1.010, defaultRefMax: 1.025, refText: '1.010 - 1.025' },
      { id: 'urn_ph', nameEn: 'pH', nameAr: 'درجة الحموضة', unit: '', defaultRefMin: 5.0, defaultRefMax: 7.5, refText: '5.0 - 7.5' },
      // Chemical
      { id: 'urn_prot', nameEn: 'Protein (Albumin)', nameAr: 'الزلال / البروتين', unit: '', refText: 'Nil / Negative', options: ['Nil / Negative', 'Trace', '+ (30 mg/dL)', '++ (100 mg/dL)', '+++ (300 mg/dL)'] },
      { id: 'urn_glu', nameEn: 'Glucose (Sugar)', nameAr: 'السكر في البول', unit: '', refText: 'Nil / Negative', options: ['Nil / Negative', 'Trace', '+ (100 mg/dL)', '++ (250 mg/dL)', '+++ (500 mg/dL)'] },
      { id: 'urn_ket', nameEn: 'Ketones (Acetone)', nameAr: 'الأسيتون والكيتون', unit: '', refText: 'Negative', options: ['Negative', 'Trace', '+ (Small)', '++ (Moderate)', '+++ (Large)'] },
      { id: 'urn_bili', nameEn: 'Bilirubin', nameAr: 'الصفراء', unit: '', refText: 'Negative', options: ['Negative', 'Positive (+)'] },
      { id: 'urn_nitrite', nameEn: 'Nitrite', nameAr: 'النتريت (دلالة بكتيريا)', unit: '', refText: 'Negative', options: ['Negative', 'Positive (+)'] },
      { id: 'urn_leuk', nameEn: 'Leukocyte Esterase', nameAr: 'إنزيم الصديد', unit: '', refText: 'Negative', options: ['Negative', 'Trace', '+ (Small)', '++ (Moderate)', '+++ (Large)'] },
      // Microscopic
      { id: 'urn_pus', nameEn: 'Pus Cells (WBCs)', nameAr: 'خلايا الصديد / صديد البول', unit: '/HPF', defaultRefMin: 0, defaultRefMax: 5, refText: '0 - 5 /HPF' },
      { id: 'urn_rbc', nameEn: 'Red Blood Cells (RBCs)', nameAr: 'كرات الدم الحمراء', unit: '/HPF', defaultRefMin: 0, defaultRefMax: 3, refText: '0 - 3 /HPF' },
      { id: 'urn_epi', nameEn: 'Epithelial Cells', nameAr: 'الخلايا الطلائية', unit: '/HPF', refText: 'Few /HPF', options: ['Nil', 'Few', 'Moderate', 'Numerous'] },
      { id: 'urn_crystals', nameEn: 'Crystals', nameAr: 'الأملاح والبلورات', unit: '', refText: 'Nil / Few', options: ['Nil', 'Calcium Oxalate (Few)', 'Calcium Oxalate (Moderate)', 'Calcium Oxalate (Many)', 'Uric Acid Crystals (Few)', 'Triple Phosphate (Few)', 'Amorphous Urates (Few)', 'Amorphous Urates (Moderate)', 'Amorphous Phosphates (Few)'] },
      { id: 'urn_casts', nameEn: 'Casts', nameAr: 'الاسطوانات البولية', unit: '', refText: 'Nil / Occasional Hyaline', options: ['Nil', 'Hyaline Casts (Few)', 'Granular Casts (Few)', 'Cellular Casts'] },
      { id: 'urn_bac', nameEn: 'Bacteria', nameAr: 'البكتيريا', unit: '', refText: 'Nil', options: ['Nil', 'Few', 'Moderate', 'Many'] }
    ]
  },
  {
    id: 'test-stool',
    code: 'STL-11',
    nameEn: 'Complete Stool Analysis',
    nameAr: 'تحليل البراز الكامل والطفيليات',
    category: 'stool',
    categoryAr: 'الفحص الميكروسكوبي وسوائل الجسم',
    sampleType: 'Fresh Stool Specimen',
    tubeColor: 'sterile_cup',
    tubeName: 'وعاء معقم لجمع عينات البراز (Stool Container)',
    turnaroundHours: 2,
    fastingHours: 0,
    instructionsAr: 'توصيل العينة للمختبر خلال ساعتين كحد أقصى من الجمع. تجنب اختلاطها بالبول أو الماء.',
    price: 90,
    parameters: [
      { id: 'stl_consistency', nameEn: 'Consistency', nameAr: 'القوام', unit: '', refText: 'Formed / Soft', options: ['Formed', 'Semi-formed', 'Soft', 'Watery', 'Loose'] },
      { id: 'stl_color', nameEn: 'Color', nameAr: 'اللون', unit: '', refText: 'Brown', options: ['Brown', 'Dark Brown', 'Yellowish', 'Clay', 'Greenish', 'Blackish'] },
      { id: 'stl_mucus', nameEn: 'Mucus', nameAr: 'المخاط', unit: '', refText: 'Nil', options: ['Nil', 'Present (+)', 'Abundant (++)'] },
      { id: 'stl_blood', nameEn: 'Blood', nameAr: 'الدم الظاهري', unit: '', refText: 'Nil', options: ['Nil', 'Present (+)'] },
      { id: 'stl_pus', nameEn: 'Pus Cells (WBCs)', nameAr: 'خلايا الصديد', unit: '/HPF', defaultRefMin: 0, defaultRefMax: 4, refText: '0 - 4 /HPF' },
      { id: 'stl_rbc', nameEn: 'RBCs', nameAr: 'كرات الدم الحمراء', unit: '/HPF', defaultRefMin: 0, defaultRefMax: 2, refText: '0 - 2 /HPF' },
      { id: 'stl_parasites', nameEn: 'Parasites & Protozoa', nameAr: 'الطفيليات والأطوار المتكيسة', unit: '', refText: 'No parasites seen', options: ['No parasites or cysts seen', 'Entamoeba histolytica cysts seen', 'Entamoeba histolytica trophozoites', 'Giardia lamblia cysts seen', 'Giardia lamblia trophozoites', 'Blastocystis hominis seen', 'Ascaris lumbricoides ova', 'Ancylostoma ova', 'Enterobius vermicularis (Oxyuris)'] },
      { id: 'stl_fats', nameEn: 'Fat Globules', nameAr: 'قطرات الدهون غير المهضومة', unit: '', refText: 'Nil / Few', options: ['Nil', 'Few', 'Moderate', 'Many'] },
      { id: 'stl_occult', nameEn: 'Occult Blood (FOB)', nameAr: 'الدم الخفي بالبراز', unit: '', refText: 'Negative', options: ['Negative', 'Positive (+)'] }
    ]
  },
  {
    id: 'test-crp',
    code: 'CRP-12',
    nameEn: 'C-Reactive Protein (Quantitative CRP)',
    nameAr: 'تحليل دلالات الالتهاب الحاد (CRP رقمي فائق الحساسية)',
    category: 'serology',
    categoryAr: 'المناعة والدلالات السيرولوجية',
    sampleType: 'Serum (Gel Separator)',
    tubeColor: 'yellow',
    tubeName: 'أنبوب جل أصفر (Gel SST)',
    turnaroundHours: 2,
    fastingHours: 0,
    instructionsAr: 'لا يتطلب صيام مسبق.',
    price: 150,
    parameters: [
      { id: 'crp_val', nameEn: 'C-Reactive Protein (hs-CRP)', nameAr: 'بروتين سي التفاعلي', unit: 'mg/L', defaultRefMin: 0.0, defaultRefMax: 6.0, refText: '< 6.0 mg/L (Normal) | 6.0 - 10.0 (Mild inflammation) | > 10.0 (Active infection / inflammation)' }
    ]
  },
  {
    id: 'test-acr',
    code: 'ACR-13',
    nameEn: 'Albumin / Creatinine Ratio in Urine (ACR)',
    nameAr: 'نسبة الزلال الدقيق إلى الكرياتينين في البول (ACR)',
    category: 'kidney',
    categoryAr: 'وظائف الكلى والأملاح',
    sampleType: 'Random / First Morning Urine',
    tubeColor: 'sterile_cup',
    tubeName: 'وعاء معقم لجمع عينات البول (Sterile Container)',
    turnaroundHours: 2,
    fastingHours: 0,
    instructionsAr: 'يفضل أول عينة بول صباحية لتجنب تأثير المجهود البدني والوقوف الطويل.',
    price: 160,
    parameters: [
      { id: 'urine_microalb', nameEn: 'Urine Microalbumin', nameAr: 'الزلال الدقيق بالبول', unit: 'mg/L', defaultRefMin: 0, defaultRefMax: 20, refText: '< 20 mg/L' },
      { id: 'urine_creat', nameEn: 'Urine Creatinine', nameAr: 'كرياتينين البول', unit: 'mg/dL', defaultRefMin: 20, defaultRefMax: 250, refText: '20 - 250 mg/dL' },
      { id: 'acr_ratio', nameEn: 'Albumin/Creatinine Ratio (ACR)', nameAr: 'نسبة الزلال إلى الكرياتينين (محسوبة)', unit: 'mg/g', defaultRefMin: 0, defaultRefMax: 30, refText: '< 30 Normal | 30 - 300 Microalbuminuria | > 300 Overt Proteinuria', isCalculated: true }
    ]
  }
];

export const INITIAL_TESTS: LabTest[] = [...BASE_TESTS, ...EXTRA_TESTS];

export const INITIAL_PACKAGES: HealthPackage[] = [

  {
    id: 'pkg-golden',
    titleAr: 'باقة الفحص الشامل الذهبي (Full Body Health)',
    titleEn: 'Golden Comprehensive Checkup',
    badge: 'الأكثر شمولاً ومبيعاً ⭐',
    descriptionAr: 'فحص متكامل يشمل أكثر من 40 دلالة حيوية: صورة دم كاملة، وظائف الكبد، الكلى، السكر التراكمي والصائم، دهون الدم الكاملة، فيتامين د3، ب12، الغدة الدرقية، والبول.',
    testIds: ['test-cbc', 'test-liver', 'test-kidney', 'test-diabetes', 'test-lipids', 'test-thyroid', 'test-vitamins', 'test-urine'],
    originalPrice: 1940,
    discountedPrice: 1190,
    iconName: 'Sparkles',
    popular: true
  },
  {
    id: 'pkg-annual',
    titleAr: 'باقة الاطمئنان الدوري السنوي',
    titleEn: 'Annual Preventive Health Screen',
    badge: 'للاطمئنان السنوي 🛡️',
    descriptionAr: 'صورة دم كاملة، سكر صائم وتراكمي، كوليسترول ودهون ثلاثية، وظائف كبد وكلى، وتحليل بول كامل.',
    testIds: ['test-cbc', 'test-liver', 'test-kidney', 'test-diabetes', 'test-lipids', 'test-urine'],
    originalPrice: 1130,
    discountedPrice: 750,
    iconName: 'ShieldCheck',
    popular: true
  },
  {
    id: 'pkg-diabetes',
    titleAr: 'باقة متابعة السكري ومقاومة الإنسولين',
    titleEn: 'Diabetes & Metabolic Health',
    badge: 'لمرضى السكر 🩺',
    descriptionAr: 'فحص سكر صائم، تراكمي HbA1c، متوسط السكر التقديري، إنسولين صائم، مؤشر HOMA-IR، كوليسترول ودهون الدم، وتحليل الكرياتينين والزلال.',
    testIds: ['test-diabetes', 'test-lipids', 'test-kidney'],
    originalPrice: 680,
    discountedPrice: 480,
    iconName: 'Activity'
  },
  {
    id: 'pkg-vitamins-energy',
    titleAr: 'باقة النشاط وعلاج الإرهاق وتساقط الشعر',
    titleEn: 'Vitamins, Fatigue & Hair Loss Panel',
    badge: 'للنشاط والحيوية ⚡',
    descriptionAr: 'صورة دم كاملة للأنيميا، فيتامين د3، فيتامين ب12، مخزون الحديد (فيريتين)، حديد الدم، وتحليل هرمون الغدة الدرقية TSH.',
    testIds: ['test-cbc', 'test-vitamins', 'test-thyroid'],
    originalPrice: 990,
    discountedPrice: 690,
    iconName: 'Zap'
  },
  {
    id: 'pkg-liver-kidney',
    titleAr: 'باقة سلامة الكبد والكلى والأملاح',
    titleEn: 'Liver & Renal Vital Profile',
    badge: 'وظائف الأعضاء الحيوية 🔬',
    descriptionAr: 'إنزيمات الكبد ALT و AST والصفراء والبروتينات، كرياتينين، بولينا، حمض اليوريك، الصوديوم والبوتاسيوم، ومعدل الترشيح eGFR.',
    testIds: ['test-liver', 'test-kidney', 'test-urine'],
    originalPrice: 550,
    discountedPrice: 390,
    iconName: 'HeartPulse'
  }
];

export const INITIAL_SETTINGS: LabSettings = {
  labNameAr: 'معامل RT LAB للتحاليل التشخيصية',
  labNameEn: 'RT LAB Diagnostic Laboratories',
  subTitleAr: 'معامل رامي مختار للتحاليل الطبية والباثولوجيا الإكلينيكية',
  directorNameAr: 'أ.د / رحاب على عبد الحميد',
  directorTitleAr: 'استشاري وأخصائي الباثولوجيا الإكلينيكية والتحاليل الطبية',
  clinicalDoctorNameAr: 'د. رامي مختار',
  clinicalDoctorTitleAr: 'طبيب الباثولوجيا الإكلينيكية - كلية طب قصر العيني',
  phonePrimary: '01100874444',
  phoneSecondary: '01100046841',
  phoneThird: '01013242777',
  whatsappNumber: '01100874444',
  addressAr: 'ميدان بهتيم - برج صيدلية العزبي - الدور الثالث - شبرا الخيمة',
  branchMain: 'الفرع الرئيسي: ميدان بهتيم برج صيدلية العزبي الدور الثالث شبرا الخيمة',
  email: 'info@rtlab-ramy.com',
  website: 'www.rtlab-ramy.com',
  sealTextAr: 'معامل RT LAB - معامل رامي مختار - معتمد وموثق',
  headerTheme: 'crimson_blue',
  ceoSharePercentage: 40,
  labSharePercentage: 60,
  pointsPerPoundSpent: 0.1,
  defaultDiscountPercentage: 15
};

export const INITIAL_ORDERS: LabOrder[] = [
  {
    id: 'order-101',
    orderNumber: 'RT-2026-00891',
    sampleBarcode: 'SMP-2026-891',
    patientId: 'pat-001',
    patientName: 'أحمد محمود عبد الرحمن',
    patientAge: 42,
    patientGender: 'male',
    patientPhone: '01012345678',
    referringDoctor: 'د. خالد إبراهيم (استشاري الباطنة والسكري)',
    branch: 'الفرع الرئيسي - المهندسين',
    bookingId: 'bk-501',
    sampleCollectionDate: '2026-09-28 08:30 ص',
    reportReleaseDate: '2026-09-28 11:45 ص',
    testIds: ['test-cbc', 'test-liver', 'test-kidney', 'test-diabetes', 'test-lipids'],
    overallStatus: 'released',
    technicianName: 'كيميائي / محمود الشناوي',
    verifiedByDoctor: 'أ.د. رامي طاهر السعيد',
    clinicalRemarks: 'يلاحظ ارتفاع طفيف في السكر الصائم والكوليسترول الضار LDL. وظائف الكبد والكلى والدم ضمن الحدود الطبيعية الممتازة. ينصح بالمتابعة الغذائية وضبط السعرات.',
    createdAt: '2026-09-28T08:30:00Z',
    results: {
      // CBC
      'hb': { paramId: 'hb', testId: 'test-cbc', paramNameEn: 'Hemoglobin (Hb)', paramNameAr: 'الهيموجلوبين', value: '14.8', numericValue: 14.8, unit: 'g/dL', refRange: '13.0 - 17.5', flag: 'NORMAL' },
      'rbc': { paramId: 'rbc', testId: 'test-cbc', paramNameEn: 'RBC Count', paramNameAr: 'كرات الدم الحمراء', value: '5.12', numericValue: 5.12, unit: 'x10^6/uL', refRange: '4.5 - 5.9', flag: 'NORMAL' },
      'hct': { paramId: 'hct', testId: 'test-cbc', paramNameEn: 'Hematocrit (PCV)', paramNameAr: 'نسبة حجم الخلايا المكدسة', value: '44.5', numericValue: 44.5, unit: '%', refRange: '40.0 - 50.0', flag: 'NORMAL' },
      'mcv': { paramId: 'mcv', testId: 'test-cbc', paramNameEn: 'MCV', paramNameAr: 'متوسط حجم الخلية', value: '87.0', numericValue: 87.0, unit: 'fL', refRange: '80.0 - 98.0', flag: 'NORMAL' },
      'mch': { paramId: 'mch', testId: 'test-cbc', paramNameEn: 'MCH', paramNameAr: 'متوسط وزن الهيموجلوبين', value: '28.9', numericValue: 28.9, unit: 'pg', refRange: '27.0 - 33.0', flag: 'NORMAL' },
      'mchc': { paramId: 'mchc', testId: 'test-cbc', paramNameEn: 'MCHC', paramNameAr: 'تركيز الهيموجلوبين بالكرية', value: '33.2', numericValue: 33.2, unit: 'g/dL', refRange: '32.0 - 36.0', flag: 'NORMAL' },
      'rdw': { paramId: 'rdw', testId: 'test-cbc', paramNameEn: 'RDW-CV', paramNameAr: 'مؤشر تباين حجم الكرات الحمراء', value: '12.8', numericValue: 12.8, unit: '%', refRange: '11.5 - 14.5', flag: 'NORMAL' },
      'plt': { paramId: 'plt', testId: 'test-cbc', paramNameEn: 'Platelets Count', paramNameAr: 'الصفائح الدموية', value: '285', numericValue: 285, unit: 'x10^3/uL', refRange: '150 - 450', flag: 'NORMAL' },
      'wbc': { paramId: 'wbc', testId: 'test-cbc', paramNameEn: 'Total WBC Count', paramNameAr: 'إجمالي كرات الدم البيضاء', value: '7.4', numericValue: 7.4, unit: 'x10^3/uL', refRange: '4.0 - 11.0', flag: 'NORMAL' },
      'neut_pct': { paramId: 'neut_pct', testId: 'test-cbc', paramNameEn: 'Neutrophils %', paramNameAr: 'الخلايا المتعادلة %', value: '58.0', numericValue: 58.0, unit: '%', refRange: '40.0 - 70.0', flag: 'NORMAL' },
      'lymph_pct': { paramId: 'lymph_pct', testId: 'test-cbc', paramNameEn: 'Lymphocytes %', paramNameAr: 'الخلايا الليمفاوية %', value: '32.0', numericValue: 32.0, unit: '%', refRange: '20.0 - 45.0', flag: 'NORMAL' },
      'mono_pct': { paramId: 'mono_pct', testId: 'test-cbc', paramNameEn: 'Monocytes %', paramNameAr: 'الخلايا وحيدة النواة %', value: '6.0', numericValue: 6.0, unit: '%', refRange: '2.0 - 8.0', flag: 'NORMAL' },
      'eos_pct': { paramId: 'eos_pct', testId: 'test-cbc', paramNameEn: 'Eosinophils %', paramNameAr: 'الخلايا الحمضية %', value: '3.0', numericValue: 3.0, unit: '%', refRange: '1.0 - 5.0', flag: 'NORMAL' },
      'baso_pct': { paramId: 'baso_pct', testId: 'test-cbc', paramNameEn: 'Basophils %', paramNameAr: 'الخلايا القاعدية %', value: '1.0', numericValue: 1.0, unit: '%', refRange: '0.0 - 1.0', flag: 'NORMAL' },
      
      // Liver
      'alt': { paramId: 'alt', testId: 'test-liver', paramNameEn: 'ALT (SGPT)', paramNameAr: 'إنزيم الكبد (ALT)', value: '28', numericValue: 28, unit: 'U/L', refRange: 'Up to 45', flag: 'NORMAL' },
      'ast': { paramId: 'ast', testId: 'test-liver', paramNameEn: 'AST (SGOT)', paramNameAr: 'إنزيم الكبد (AST)', value: '24', numericValue: 24, unit: 'U/L', refRange: 'Up to 40', flag: 'NORMAL' },
      'tot_bili': { paramId: 'tot_bili', testId: 'test-liver', paramNameEn: 'Total Bilirubin', paramNameAr: 'الصفراء الكلية بالدم', value: '0.85', numericValue: 0.85, unit: 'mg/dL', refRange: '0.2 - 1.2', flag: 'NORMAL' },
      'dir_bili': { paramId: 'dir_bili', testId: 'test-liver', paramNameEn: 'Direct Bilirubin', paramNameAr: 'الصفراء المباشرة', value: '0.18', numericValue: 0.18, unit: 'mg/dL', refRange: 'Up to 0.3', flag: 'NORMAL' },
      'indir_bili': { paramId: 'indir_bili', testId: 'test-liver', paramNameEn: 'Indirect Bilirubin', paramNameAr: 'الصفراء غير المباشرة (محسوبة)', value: '0.67', numericValue: 0.67, unit: 'mg/dL', refRange: '0.1 - 0.8', flag: 'NORMAL' },
      'alp': { paramId: 'alp', testId: 'test-liver', paramNameEn: 'Alkaline Phosphatase (ALP)', paramNameAr: 'الفوسفاتاز القلوي', value: '82', numericValue: 82, unit: 'U/L', refRange: '40 - 130', flag: 'NORMAL' },
      'tot_prot': { paramId: 'tot_prot', testId: 'test-liver', paramNameEn: 'Total Protein', paramNameAr: 'البروتين الكلي', value: '7.3', numericValue: 7.3, unit: 'g/dL', refRange: '6.4 - 8.3', flag: 'NORMAL' },
      'albumin': { paramId: 'albumin', testId: 'test-liver', paramNameEn: 'Serum Albumin', paramNameAr: 'الألبومين', value: '4.4', numericValue: 4.4, unit: 'g/dL', refRange: '3.5 - 5.2', flag: 'NORMAL' },
      'globulin': { paramId: 'globulin', testId: 'test-liver', paramNameEn: 'Serum Globulin', paramNameAr: 'الجلوبيولين (محسوب)', value: '2.9', numericValue: 2.9, unit: 'g/dL', refRange: '2.0 - 3.5', flag: 'NORMAL' },
      'ag_ratio': { paramId: 'ag_ratio', testId: 'test-liver', paramNameEn: 'A/G Ratio', paramNameAr: 'نسبة الألبومين للجلوبيولين', value: '1.52', numericValue: 1.52, unit: 'Ratio', refRange: '1.2 - 2.2', flag: 'NORMAL' },

      // Kidney
      'creatinine': { paramId: 'creatinine', testId: 'test-kidney', paramNameEn: 'Serum Creatinine', paramNameAr: 'الكرياتينين بالدم', value: '0.95', numericValue: 0.95, unit: 'mg/dL', refRange: '0.7 - 1.2', flag: 'NORMAL' },
      'urea': { paramId: 'urea', testId: 'test-kidney', paramNameEn: 'Blood Urea', paramNameAr: 'البولينا بالدم (اليوريا)', value: '28.0', numericValue: 28.0, unit: 'mg/dL', refRange: '15 - 45', flag: 'NORMAL' },
      'uric_acid': { paramId: 'uric_acid', testId: 'test-kidney', paramNameEn: 'Serum Uric Acid', paramNameAr: 'حمض اليوريك (النقرس)', value: '5.4', numericValue: 5.4, unit: 'mg/dL', refRange: '3.5 - 7.2', flag: 'NORMAL' },
      'egfr': { paramId: 'egfr', testId: 'test-kidney', paramNameEn: 'eGFR (CKD-EPI)', paramNameAr: 'معدل الترشيح الكلوي التقديري', value: '98', numericValue: 98, unit: 'mL/min/1.73m2', refRange: '> 90', flag: 'NORMAL' },
      'sodium': { paramId: 'sodium', testId: 'test-kidney', paramNameEn: 'Sodium (Na+)', paramNameAr: 'الصوديوم', value: '141', numericValue: 141, unit: 'mmol/L', refRange: '135 - 145', flag: 'NORMAL' },
      'potassium': { paramId: 'potassium', testId: 'test-kidney', paramNameEn: 'Potassium (K+)', paramNameAr: 'البوتاسيوم', value: '4.2', numericValue: 4.2, unit: 'mmol/L', refRange: '3.5 - 5.1', flag: 'NORMAL' },

      // Diabetes
      'fbg': { paramId: 'fbg', testId: 'test-diabetes', paramNameEn: 'Fasting Blood Glucose', paramNameAr: 'السكر الصائم بالدم', value: '112', numericValue: 112, unit: 'mg/dL', refRange: '70 - 99', flag: 'HIGH', notes: 'مرحلة ما قبل السكري (Prediabetes)' },
      'hba1c': { paramId: 'hba1c', testId: 'test-diabetes', paramNameEn: 'HbA1c (Glycated Hemoglobin)', paramNameAr: 'السكر التراكمي (الهيموجلوبين السكري)', value: '5.9', numericValue: 5.9, unit: '%', refRange: '< 5.7', flag: 'HIGH', notes: 'معدل تراكمي مرتفع نسبياً (Prediabetic zone)' },
      'eag': { paramId: 'eag', testId: 'test-diabetes', paramNameEn: 'Estimated Average Glucose (eAG)', paramNameAr: 'متوسط السكر التقديري المحسوب', value: '123', numericValue: 123, unit: 'mg/dL', refRange: '68 - 114', flag: 'HIGH' },
      'fasting_insulin': { paramId: 'fasting_insulin', testId: 'test-diabetes', paramNameEn: 'Fasting Serum Insulin', paramNameAr: 'إنسولين الدم الصائم', value: '14.5', numericValue: 14.5, unit: 'uIU/mL', refRange: '2.6 - 24.9', flag: 'NORMAL' },
      'homa_ir': { paramId: 'homa_ir', testId: 'test-diabetes', paramNameEn: 'HOMA-IR (Insulin Resistance)', paramNameAr: 'مؤشر مقاومة الإنسولين (HOMA-IR)', value: '4.01', numericValue: 4.01, unit: 'Index', refRange: '< 1.9', flag: 'HIGH', notes: 'مقاومة إنسولين ملحوظة تستدعي حمية وممارسة الرياضة' },

      // Lipids
      'chol': { paramId: 'chol', testId: 'test-lipids', paramNameEn: 'Total Cholesterol', paramNameAr: 'الكوليسترول الكلي', value: '218', numericValue: 218, unit: 'mg/dL', refRange: '< 200', flag: 'HIGH' },
      'trig': { paramId: 'trig', testId: 'test-lipids', paramNameEn: 'Triglycerides', paramNameAr: 'الدهون الثلاثية', value: '165', numericValue: 165, unit: 'mg/dL', refRange: '< 150', flag: 'HIGH' },
      'hdl': { paramId: 'hdl', testId: 'test-lipids', paramNameEn: 'HDL Cholesterol (Good)', paramNameAr: 'الكوليسترول عالي الكثافة (النافع)', value: '44', numericValue: 44, unit: 'mg/dL', refRange: '> 40', flag: 'NORMAL' },
      'ldl': { paramId: 'ldl', testId: 'test-lipids', paramNameEn: 'LDL Cholesterol (Bad)', paramNameAr: 'الكوليسترول منخفض الكثافة (الضار)', value: '141', numericValue: 141, unit: 'mg/dL', refRange: '< 100', flag: 'HIGH' },
      'vldl': { paramId: 'vldl', testId: 'test-lipids', paramNameEn: 'VLDL Cholesterol', paramNameAr: 'كوليسترول منخفض الكثافة جداً', value: '33', numericValue: 33, unit: 'mg/dL', refRange: '10 - 30', flag: 'HIGH' },
      'chol_hdl_ratio': { paramId: 'chol_hdl_ratio', testId: 'test-lipids', paramNameEn: 'Cholesterol / HDL Ratio', paramNameAr: 'مؤشر خطورة تصلب الشرايين', value: '4.95', numericValue: 4.95, unit: 'Ratio', refRange: '< 4.5', flag: 'HIGH' }
    }
  },
  {
    id: 'order-102',
    orderNumber: 'RT-2026-00892',
    sampleBarcode: 'SMP-2026-892',
    patientId: 'pat-002',
    patientName: 'مريم إبراهيم حسن',
    patientAge: 29,
    patientGender: 'female',
    patientPhone: '01123456789',
    referringDoctor: 'د. نادية كمال (استشاري الغدد الصماء)',
    branch: 'فرع مدينة نصر',
    sampleCollectionDate: '2026-09-28 09:15 ص',
    testIds: ['test-thyroid', 'test-vitamins', 'test-cbc'],
    overallStatus: 'partially_entered',
    technicianName: 'كيميائي / ريهام عزمي',
    verifiedByDoctor: 'أ.د. رامي طاهر السعيد',
    clinicalRemarks: 'جاري استكمال فحص فيتامين د على جهاز الكيميلومينيسينس.',
    createdAt: '2026-09-28T09:15:00Z',
    results: {
      'tsh': { paramId: 'tsh', testId: 'test-thyroid', paramNameEn: 'TSH (Ultrasensitive)', paramNameAr: 'الهرمون المنبه للغدة الدرقية (TSH)', value: '6.45', numericValue: 6.45, unit: 'uIU/mL', refRange: '0.4 - 4.2', flag: 'HIGH', notes: 'خمول أولي في نشاط الغدة الدرقية (Subclinical Hypothyroidism)' },
      'ft3': { paramId: 'ft3', testId: 'test-thyroid', paramNameEn: 'Free T3 (FT3)', paramNameAr: 'هرمون ثلاثي اليودوثيرونين الحر', value: '2.8', numericValue: 2.8, unit: 'pg/mL', refRange: '2.0 - 4.4', flag: 'NORMAL' },
      'ft4': { paramId: 'ft4', testId: 'test-thyroid', paramNameEn: 'Free T4 (FT4)', paramNameAr: 'هرمون الثيروكسين الحر', value: '1.05', numericValue: 1.05, unit: 'ng/dL', refRange: '0.93 - 1.70', flag: 'NORMAL' },
      'vit_b12': { paramId: 'vit_b12', testId: 'test-vitamins', paramNameEn: 'Vitamin B12 (Cobalamin)', paramNameAr: 'فيتامين ب12', value: '185', numericValue: 185, unit: 'pg/mL', refRange: '200 - 900', flag: 'LOW', notes: 'نقص في فيتامين ب12 يستوجب العلاج التعويضي' },
      'ferritin': { paramId: 'ferritin', testId: 'test-vitamins', paramNameEn: 'Serum Ferritin', paramNameAr: 'الفيريتين (مخزون الحديد)', value: '12.4', numericValue: 12.4, unit: 'ng/mL', refRange: '15 - 200', flag: 'LOW', notes: 'استنزاف مخزون الحديد' }
    }
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-501',
    bookingNumber: 'RT-BK-2026-8941',
    patientName: 'أحمد محمود عبد الرحمن',
    patientPhone: '01012345678',
    patientAge: 42,
    patientGender: 'male',
    serviceType: 'home_visit',
    address: 'شارع شهاب، عمارة 15، الدور الرابع شقة 8، المهندسين، الجيزة',
    area: 'المهندسين - الجيزة',
    visitDate: '2026-09-28',
    visitTime: '08:30 ص',
    selectedTestIds: ['test-cbc', 'test-liver', 'test-kidney', 'test-diabetes', 'test-lipids'],
    selectedPackageId: 'pkg-annual',
    notes: 'المريض يعاني من دوخة بسيطة، يرجى إحضار فني خبير لسحب الأوردة الدقيقة.',
    totalPrice: 1130,
    discount: 380,
    finalPrice: 750,
    status: 'completed',
    technicianName: 'كيميائي / هاني عبد الفتاح',
    transferredToLisOrderId: 'order-101',
    createdAt: '2026-09-27T18:20:00Z'
  },
  {
    id: 'bk-502',
    bookingNumber: 'RT-BK-2026-8942',
    patientName: 'سارة طارق النجار',
    patientPhone: '01287654321',
    patientAge: 34,
    patientGender: 'female',
    serviceType: 'home_visit',
    address: 'كمبوند بالم هيلز، فيلا 42، التجمع الخامس، القاهرة الجديدة',
    area: 'التجمع الخامس - القاهرة الجديدة',
    visitDate: '2026-09-29',
    visitTime: '09:00 ص',
    selectedTestIds: ['test-cbc', 'test-vitamins', 'test-thyroid'],
    selectedPackageId: 'pkg-vitamins-energy',
    notes: 'تحليل دوري مع الصيام 8 ساعات.',
    totalPrice: 990,
    discount: 300,
    finalPrice: 690,
    status: 'technician_assigned',
    technicianName: 'ممرض / كريم الدسوقي',
    createdAt: '2026-09-28T10:15:00Z'
  },
  {
    id: 'bk-503',
    bookingNumber: 'RT-BK-2026-8943',
    patientName: 'د. يحيى خليل رضوان',
    patientPhone: '01055443322',
    patientAge: 58,
    patientGender: 'male',
    serviceType: 'lab_branch',
    branchName: 'فرع مدينة نصر (شارع عباس العقاد)',
    address: 'فرع المختبر مباشرة',
    area: 'مدينة نصر',
    visitDate: '2026-09-29',
    visitTime: '10:30 ص',
    selectedTestIds: ['test-cbc', 'test-liver', 'test-kidney', 'test-diabetes', 'test-lipids', 'test-thyroid', 'test-vitamins', 'test-urine'],
    selectedPackageId: 'pkg-golden',
    notes: 'حجز زيارة فرع - باقة الفحص الشامل الذهبي.',
    totalPrice: 1940,
    discount: 750,
    finalPrice: 1190,
    status: 'confirmed',
    createdAt: '2026-09-28T11:40:00Z'
  }
];

export const INITIAL_LOYALTY_CARDS: LoyaltyCard[] = [
  {
    id: 'card-1',
    cardNumber: 'RT-LOYAL-501',
    patientName: 'أحمد محمود عبد الرحمن',
    patientPhone: '01012345678',
    tier: 'gold',
    tierNameAr: 'البطاقة الذهبية (Gold)',
    discountPercentage: 15,
    pointsBalance: 140,
    totalVisits: 4,
    issueDate: '2026-01-15',
    expiryDate: '2027-01-15',
    status: 'active',
    barcode: 'RT-LOYAL-501'
  },
  {
    id: 'card-2',
    cardNumber: 'RT-LOYAL-502',
    patientName: 'سارة طارق النجار',
    patientPhone: '01287654321',
    tier: 'platinum',
    tierNameAr: 'البطاقة البلاتينية VIP (Platinum)',
    discountPercentage: 25,
    pointsBalance: 320,
    totalVisits: 7,
    issueDate: '2026-02-01',
    expiryDate: '2027-02-01',
    status: 'active',
    barcode: 'RT-LOYAL-502'
  },
  {
    id: 'card-3',
    cardNumber: 'RT-LOYAL-503',
    patientName: 'د. يحيى خليل رضوان',
    patientPhone: '01055443322',
    tier: 'syndicate',
    tierNameAr: 'كارت نقابة الأطباء (Syndicate)',
    discountPercentage: 30,
    pointsBalance: 450,
    totalVisits: 9,
    issueDate: '2025-11-20',
    expiryDate: '2026-11-20',
    status: 'active',
    barcode: 'RT-LOYAL-503'
  },
  {
    id: 'card-4',
    cardNumber: 'RT-LOYAL-504',
    patientName: 'عائلة المستشار علاء الشريف',
    patientPhone: '01155667788',
    tier: 'family',
    tierNameAr: 'كارت العائلة الموحد (Family)',
    discountPercentage: 20,
    pointsBalance: 210,
    totalVisits: 5,
    issueDate: '2026-03-10',
    expiryDate: '2027-03-10',
    status: 'active',
    barcode: 'RT-LOYAL-504'
  }
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'staff-rehab',
    code: 'EMP-01',
    name: 'أ.د / رحاب على عبد الحميد',
    role: 'technical_director',
    roleAr: 'المدير الفني للمختبر',
    titleDescription: 'استشاري وأخصائي الباثولوجيا الإكلينيكية والتحاليل الطبية',
    department: 'الإدارة الفنية وضبط الجودة',
    phone: '01100874444',
    nationalId: '27505120101234',
    hireDate: '2019-01-01',
    baseSalary: 28000,
    shift: 'morning',
    status: 'active',
    incentives: 3000,
    bonuses: 1500,
    deductions: 0,
    overtimeHours: 6,
    overtimeHourlyRate: 200
  },
  {
    id: 'staff-ramy',
    code: 'EMP-02',
    name: 'د. رامي مختار',
    role: 'consultant_doctor',
    roleAr: 'طبيب الباثولوجيا الإكلينيكية',
    titleDescription: 'طبيب الباثولوجيا الإكلينيكية - كلية طب قصر العيني',
    department: 'قسم التشخيص والاستشارات الطبية',
    phone: '01013242777',
    nationalId: '28409150102345',
    hireDate: '2019-01-01',
    baseSalary: 30000,
    shift: 'morning',
    status: 'active',
    incentives: 4000,
    bonuses: 2000,
    deductions: 0,
    overtimeHours: 10,
    overtimeHourlyRate: 220
  },
  {
    id: 'staff-hani',
    code: 'EMP-03',
    name: 'كيميائي / هاني عبد الفتاح',
    role: 'lab_specialist',
    roleAr: 'أخصائي أول كيمياء وسيرولوجي',
    titleDescription: 'أخصائي الكيمياء الإكلينيكية والتشخيص المخبري',
    department: 'قسم الكيمياء الإكلينيكية',
    phone: '01100046841',
    nationalId: '29204120108976',
    hireDate: '2021-02-15',
    baseSalary: 9200,
    shift: 'morning',
    status: 'active',
    incentives: 1200,
    bonuses: 500,
    deductions: 100,
    overtimeHours: 12,
    overtimeHourlyRate: 75
  },
  {
    id: 'staff-reham',
    code: 'EMP-04',
    name: 'كيميائية / ريهام عزمي',
    role: 'lab_specialist',
    roleAr: 'أخصائية أمراض دم وهرمونات',
    titleDescription: 'أخصائية الهماتولوجي والمناعة الطبية',
    department: 'قسم الهرمونات والهماتولوجي',
    phone: '01100874444',
    nationalId: '29508190104523',
    hireDate: '2022-08-01',
    baseSalary: 8500,
    shift: 'evening',
    status: 'active',
    incentives: 900,
    bonuses: 400,
    deductions: 0,
    overtimeHours: 8,
    overtimeHourlyRate: 70
  },
  {
    id: 'staff-karim',
    code: 'EMP-05',
    name: 'ممرض وفني سحب / كريم الدسوقي',
    role: 'phlebotomist',
    roleAr: 'أخصائي سحب أوردة وزيارات منزلية',
    titleDescription: 'فني سحب العينات بالمعمل والزيارات المنزلية',
    department: 'فريق السحب والزيارات',
    phone: '01013242777',
    nationalId: '29402030107712',
    hireDate: '2023-01-10',
    baseSalary: 7000,
    shift: 'morning',
    status: 'active',
    incentives: 800,
    bonuses: 350,
    deductions: 80,
    overtimeHours: 14,
    overtimeHourlyRate: 60
  },
  {
    id: 'staff-mayada',
    code: 'EMP-06',
    name: 'أخصائية استقبال / ميادة الشريف',
    role: 'receptionist',
    roleAr: 'مسئولة خدمة العملاء والاستقبال',
    titleDescription: 'مسئولة الاستقبال وخدمات المرضى وتسجيل الحجوزات',
    department: 'قسم الاستقبال والحسابات',
    phone: '01100046841',
    nationalId: '29811050106644',
    hireDate: '2023-06-20',
    baseSalary: 5800,
    shift: 'morning',
    status: 'active',
    incentives: 650,
    bonuses: 250,
    deductions: 50,
    overtimeHours: 6,
    overtimeHourlyRate: 50
  },
  {
    id: 'staff-osama',
    code: 'EMP-07',
    name: 'محاسب مالي / أسامة النجار',
    role: 'accountant',
    roleAr: 'مسئول الحسابات والخزينة',
    titleDescription: 'مسئول الإدارة المالية وحسابات المرضى والشركاء',
    department: 'الإدارة المالية',
    phone: '01100874444',
    nationalId: '29107140103321',
    hireDate: '2022-11-01',
    baseSalary: 8000,
    shift: 'morning',
    status: 'active',
    incentives: 1000,
    bonuses: 500,
    deductions: 0,
    overtimeHours: 8,
    overtimeHourlyRate: 70
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    staffId: 'staff-1',
    staffName: 'د. رامي مختار',
    staffRole: 'استشاري ورئيس المختبر',
    date: '2026-09-28',
    checkInTime: '08:45 ص',
    shift: 'morning',
    status: 'present',
    delayMinutes: 0,
    notes: 'حضور مبكر والإشراف على اعتماد عينات الصباح'
  },
  {
    id: 'att-2',
    staffId: 'staff-2',
    staffName: 'كيميائي / هاني عبد الفتاح',
    staffRole: 'أخصائي أول كيمياء وسيرولوجي',
    date: '2026-09-28',
    checkInTime: '08:55 ص',
    shift: 'morning',
    status: 'present',
    delayMinutes: 0
  },
  {
    id: 'att-3',
    staffId: 'staff-4',
    staffName: 'ممرض وفني سحب / كريم الدسوقي',
    staffRole: 'أخصائي سحب أوردة وزيارات منزلية',
    date: '2026-09-28',
    checkInTime: '09:05 ص',
    shift: 'morning',
    status: 'late',
    delayMinutes: 5,
    notes: 'تأخير بسيط بسبب حركة المرور بشارع فيصل'
  },
  {
    id: 'att-4',
    staffId: 'staff-5',
    staffName: 'أخصائية استقبال / ميادة الشريف',
    staffRole: 'مسئولة خدمة العملاء والاستقبال',
    date: '2026-09-28',
    checkInTime: '08:50 ص',
    shift: 'morning',
    status: 'present',
    delayMinutes: 0
  }
];

export const INITIAL_FINANCIALS: FinancialTransaction[] = [
  {
    id: 'tx-1',
    txNumber: 'RT-TX-1001',
    type: 'income',
    category: 'patient_receipt',
    categoryAr: 'إيراد فحص / باقة الفحص الشامل',
    amount: 1190,
    paymentMethod: 'cash',
    paymentMethodAr: 'كاش نقدي (الخزينة)',
    date: '2026-09-28',
    time: '09:30 ص',
    patientOrPartyName: 'د. يحيى خليل رضوان',
    notes: 'سداد باقة الفحص الذهبي بالكامل',
    registeredBy: 'ميادة الشريف'
  },
  {
    id: 'tx-2',
    txNumber: 'RT-TX-1002',
    type: 'income',
    category: 'patient_receipt',
    categoryAr: 'إيراد زيارة منزلية وفحوصات',
    amount: 750,
    paymentMethod: 'instapay',
    paymentMethodAr: 'إنستاباي (InstaPay)',
    date: '2026-09-28',
    time: '10:15 ص',
    patientOrPartyName: 'أحمد محمود عبد الرحمن',
    notes: 'تحويل لحظي إنستاباي لسحب منزلي',
    registeredBy: 'كريم الدسوقي'
  },
  {
    id: 'tx-3',
    txNumber: 'RT-TX-1003',
    type: 'expense',
    category: 'reagents_purchase',
    categoryAr: 'شراء كواشف CBC ومحاليل كيمياء',
    amount: 3200,
    paymentMethod: 'bank_transfer',
    paymentMethodAr: 'تحويل بنكي',
    date: '2026-09-28',
    time: '11:00 ص',
    patientOrPartyName: 'شركة النيل للكواشف الطبية',
    notes: 'شراء كواشف ALT, AST, Urea, Creatinine و Diluent',
    registeredBy: 'د. رامي مختار'
  },
  {
    id: 'tx-4',
    txNumber: 'RT-TX-1004',
    type: 'income',
    category: 'patient_receipt',
    categoryAr: 'إيراد فحص فيتامينات وغدة درقية',
    amount: 690,
    paymentMethod: 'visa',
    paymentMethodAr: 'بطاقة بنكية / فيزا POS',
    date: '2026-09-28',
    time: '11:30 ص',
    patientOrPartyName: 'سارة طارق النجار',
    notes: 'سداد بفيزا البنك الأهلي',
    registeredBy: 'ميادة الشريف'
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    code: 'CBC-DIL-01',
    nameAr: 'محلول تخفيف صورة الدم CBC Diluent 20L',
    nameEn: 'Mindray / Sysmex CBC Diluent Reagent 20L',
    category: 'reagents',
    categoryAr: 'كواشف ومحاليل كيميائية',
    currentStock: 4,
    minThreshold: 2,
    unit: 'جركن 20 لتر',
    unitPrice: 850,
    supplier: 'شركة النيل للأجهزة والكيماويات',
    lotNumber: 'LOT-26D04',
    expiryDate: '2027-05-30',
    status: 'in_stock'
  },
  {
    id: 'inv-2',
    code: 'ALT-KIT-02',
    nameAr: 'كاشف إنزيم الكبد GPT / ALT Kinetic Kit',
    nameEn: 'Biosystems ALT/GPT Kinetic UV Kit 10x20ml',
    category: 'reagents',
    categoryAr: 'كواشف ومحاليل كيميائية',
    currentStock: 2,
    minThreshold: 3,
    unit: 'طقم كواشف (Kit)',
    unitPrice: 520,
    supplier: 'شركة بايو سيستمز مصر',
    lotNumber: 'LOT-26A18',
    expiryDate: '2027-02-28',
    status: 'low_stock'
  },
  {
    id: 'inv-3',
    code: 'GLU-KIT-03',
    nameAr: 'كاشف سكر الجلوكوز Glucose Enzymatic GOD-PAP',
    nameEn: 'Spinreact Glucose GOD-PAP Kit 4x100ml',
    category: 'reagents',
    categoryAr: 'كواشف ومحاليل كيميائية',
    currentStock: 6,
    minThreshold: 2,
    unit: 'طقم كواشف (Kit)',
    unitPrice: 380,
    supplier: 'موزع سبين رياكت',
    lotNumber: 'LOT-26G90',
    expiryDate: '2027-08-15',
    status: 'in_stock'
  },
  {
    id: 'inv-4',
    code: 'TUBE-EDTA-04',
    nameAr: 'أنابيب سحب الدم إيديتا كيه 3 (Lavender EDTA K3 3ml)',
    nameEn: 'Vacutainer EDTA K3 3ml Blood Tubes (Pack of 100)',
    category: 'tubes',
    categoryAr: 'أنابيب سحب الدم',
    currentStock: 8,
    minThreshold: 4,
    unit: 'علبة (100 أنبوب)',
    unitPrice: 190,
    supplier: 'شركة الأهرام للمستلزمات الطبية',
    lotNumber: 'LOT-2026-ED8',
    expiryDate: '2028-01-30',
    status: 'in_stock'
  },
  {
    id: 'inv-5',
    code: 'TUBE-GEL-05',
    nameAr: 'أنابيب جل فاصل للكيمياء (Yellow Gel SST 4ml)',
    nameEn: 'Vacutainer Gel SST 4ml Serum Separator (Pack of 100)',
    category: 'tubes',
    categoryAr: 'أنابيب سحب الدم',
    currentStock: 3,
    minThreshold: 4,
    unit: 'علبة (100 أنبوب)',
    unitPrice: 220,
    supplier: 'شركة الأهرام للمستلزمات الطبية',
    lotNumber: 'LOT-2026-GL4',
    expiryDate: '2028-02-15',
    status: 'low_stock'
  },
  {
    id: 'inv-6',
    code: 'NEEDLE-VAC-06',
    nameAr: 'سنون سحب فاكيوتنر معقمة مقاس 21G/22G',
    nameEn: 'Sterile Multi-Sample Blood Collection Needles 21G/22G (Box of 100)',
    category: 'needles',
    categoryAr: 'سنون وسرنجات معقمة',
    currentStock: 12,
    minThreshold: 5,
    unit: 'علبة (100 سن)',
    unitPrice: 140,
    supplier: 'شركة الفتح الطبية',
    lotNumber: 'LOT-2026-ND2',
    expiryDate: '2029-05-30',
    status: 'in_stock'
  }
];

